<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Jka\jka_template.json" LogicalName="jka_template.json" />
    <EmbeddedResource Include="Jka/jka_humanoid.json" LogicalName="jka_humanoid.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ZstdSharp.Port" Version="0.8.8" />
  </ItemGroup>

</Project>
